/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as FormRouteRouteImport } from './routes/_form/route'
import { Route as AccountRouteRouteImport } from './routes/_account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormReviewRouteImport } from './routes/_form/review'
import { Route as FormPaymentRouteImport } from './routes/_form/payment'
import { Route as FormMedicalDirectorRouteImport } from './routes/_form/medical-director'
import { Route as FormLocationRouteImport } from './routes/_form/location'
import { Route as FormAcknowledgementsRouteImport } from './routes/_form/acknowledgements'
import { Route as FormAccountRouteImport } from './routes/_form/account'
import { Route as AccountAccountSetupIndexRouteImport } from './routes/_account/account-setup/index'
import { Route as AccountAccountSetupCodeIndexRouteImport } from './routes/_account/account-setup/$code/index'
import { Route as AccountAccountSetupCodeSubmittedRouteImport } from './routes/_account/account-setup/$code/submitted'

const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRouteRoute = FormRouteRouteImport.update({
  id: '/_form',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormReviewRoute = FormReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormPaymentRoute = FormPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormMedicalDirectorRoute = FormMedicalDirectorRouteImport.update({
  id: '/medical-director',
  path: '/medical-director',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormLocationRoute = FormLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormAcknowledgementsRoute = FormAcknowledgementsRouteImport.update({
  id: '/acknowledgements',
  path: '/acknowledgements',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormAccountRoute = FormAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => FormRouteRoute,
} as any)
const AccountAccountSetupIndexRoute =
  AccountAccountSetupIndexRouteImport.update({
    id: '/account-setup/',
    path: '/account-setup/',
    getParentRoute: () => AccountRouteRoute,
  } as any)
const AccountAccountSetupCodeIndexRoute =
  AccountAccountSetupCodeIndexRouteImport.update({
    id: '/account-setup/$code/',
    path: '/account-setup/$code/',
    getParentRoute: () => AccountRouteRoute,
  } as any)
const AccountAccountSetupCodeSubmittedRoute =
  AccountAccountSetupCodeSubmittedRouteImport.update({
    id: '/account-setup/$code/submitted',
    path: '/account-setup/$code/submitted',
    getParentRoute: () => AccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/submitted': typeof SubmittedRoute
  '/account': typeof FormAccountRoute
  '/acknowledgements': typeof FormAcknowledgementsRoute
  '/location': typeof FormLocationRoute
  '/medical-director': typeof FormMedicalDirectorRoute
  '/payment': typeof FormPaymentRoute
  '/review': typeof FormReviewRoute
  '/account-setup': typeof AccountAccountSetupIndexRoute
  '/account-setup/$code/submitted': typeof AccountAccountSetupCodeSubmittedRoute
  '/account-setup/$code': typeof AccountAccountSetupCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submitted': typeof SubmittedRoute
  '/account': typeof FormAccountRoute
  '/acknowledgements': typeof FormAcknowledgementsRoute
  '/location': typeof FormLocationRoute
  '/medical-director': typeof FormMedicalDirectorRoute
  '/payment': typeof FormPaymentRoute
  '/review': typeof FormReviewRoute
  '/account-setup': typeof AccountAccountSetupIndexRoute
  '/account-setup/$code/submitted': typeof AccountAccountSetupCodeSubmittedRoute
  '/account-setup/$code': typeof AccountAccountSetupCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_account': typeof AccountRouteRouteWithChildren
  '/_form': typeof FormRouteRouteWithChildren
  '/submitted': typeof SubmittedRoute
  '/_form/account': typeof FormAccountRoute
  '/_form/acknowledgements': typeof FormAcknowledgementsRoute
  '/_form/location': typeof FormLocationRoute
  '/_form/medical-director': typeof FormMedicalDirectorRoute
  '/_form/payment': typeof FormPaymentRoute
  '/_form/review': typeof FormReviewRoute
  '/_account/account-setup/': typeof AccountAccountSetupIndexRoute
  '/_account/account-setup/$code/submitted': typeof AccountAccountSetupCodeSubmittedRoute
  '/_account/account-setup/$code/': typeof AccountAccountSetupCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/submitted'
    | '/account'
    | '/acknowledgements'
    | '/location'
    | '/medical-director'
    | '/payment'
    | '/review'
    | '/account-setup'
    | '/account-setup/$code/submitted'
    | '/account-setup/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/submitted'
    | '/account'
    | '/acknowledgements'
    | '/location'
    | '/medical-director'
    | '/payment'
    | '/review'
    | '/account-setup'
    | '/account-setup/$code/submitted'
    | '/account-setup/$code'
  id:
    | '__root__'
    | '/'
    | '/_account'
    | '/_form'
    | '/submitted'
    | '/_form/account'
    | '/_form/acknowledgements'
    | '/_form/location'
    | '/_form/medical-director'
    | '/_form/payment'
    | '/_form/review'
    | '/_account/account-setup/'
    | '/_account/account-setup/$code/submitted'
    | '/_account/account-setup/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  FormRouteRoute: typeof FormRouteRouteWithChildren
  SubmittedRoute: typeof SubmittedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_form': {
      id: '/_form'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FormRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_form/review': {
      id: '/_form/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof FormReviewRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/payment': {
      id: '/_form/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof FormPaymentRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/medical-director': {
      id: '/_form/medical-director'
      path: '/medical-director'
      fullPath: '/medical-director'
      preLoaderRoute: typeof FormMedicalDirectorRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/location': {
      id: '/_form/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof FormLocationRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/acknowledgements': {
      id: '/_form/acknowledgements'
      path: '/acknowledgements'
      fullPath: '/acknowledgements'
      preLoaderRoute: typeof FormAcknowledgementsRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_form/account': {
      id: '/_form/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof FormAccountRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/_account/account-setup/': {
      id: '/_account/account-setup/'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AccountAccountSetupIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account-setup/$code/': {
      id: '/_account/account-setup/$code/'
      path: '/account-setup/$code'
      fullPath: '/account-setup/$code'
      preLoaderRoute: typeof AccountAccountSetupCodeIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_account/account-setup/$code/submitted': {
      id: '/_account/account-setup/$code/submitted'
      path: '/account-setup/$code/submitted'
      fullPath: '/account-setup/$code/submitted'
      preLoaderRoute: typeof AccountAccountSetupCodeSubmittedRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAccountSetupIndexRoute: typeof AccountAccountSetupIndexRoute
  AccountAccountSetupCodeSubmittedRoute: typeof AccountAccountSetupCodeSubmittedRoute
  AccountAccountSetupCodeIndexRoute: typeof AccountAccountSetupCodeIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAccountSetupIndexRoute: AccountAccountSetupIndexRoute,
  AccountAccountSetupCodeSubmittedRoute: AccountAccountSetupCodeSubmittedRoute,
  AccountAccountSetupCodeIndexRoute: AccountAccountSetupCodeIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface FormRouteRouteChildren {
  FormAccountRoute: typeof FormAccountRoute
  FormAcknowledgementsRoute: typeof FormAcknowledgementsRoute
  FormLocationRoute: typeof FormLocationRoute
  FormMedicalDirectorRoute: typeof FormMedicalDirectorRoute
  FormPaymentRoute: typeof FormPaymentRoute
  FormReviewRoute: typeof FormReviewRoute
}

const FormRouteRouteChildren: FormRouteRouteChildren = {
  FormAccountRoute: FormAccountRoute,
  FormAcknowledgementsRoute: FormAcknowledgementsRoute,
  FormLocationRoute: FormLocationRoute,
  FormMedicalDirectorRoute: FormMedicalDirectorRoute,
  FormPaymentRoute: FormPaymentRoute,
  FormReviewRoute: FormReviewRoute,
}

const FormRouteRouteWithChildren = FormRouteRoute._addFileChildren(
  FormRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  FormRouteRoute: FormRouteRouteWithChildren,
  SubmittedRoute: SubmittedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
